spring.application.name=backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VNPayIntegration;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#FE_URL
frontend.url=http://localhost:5173

#swaggerURl
swagger.url=http://localhost:8080/swagger-ui/index.html